story/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('story6.urls')),
    path('admin/', admin.site.urls),
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'
urlpatterns = [
    path('', views.kegiatan, name='kegiatan'),
    path('tambahKegiatan/', views.tambahKegiatan, name='tambahKegiatan'),
    path('tambahPeserta/<int:id>', views.tambahPeserta, name='tambahPeserta'),
    path('deleteKegiatan/<int:id>', views.deleteKegiatan, name="deleteKegiatan"),
]

story6/models.py
from django.db import models
from django.contrib.auth.models import User

class Kegiatan(models.Model) :
	title = models.CharField(max_length=100)

	def __str__(self):
		return self.title

class Peserta(models.Model) :
	kegiatan = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)
	nama_peserta = models.CharField(max_length=100)

	def __str__(self):
		return self.nama_peserta

story6/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Kegiatan, Peserta
from django.db import models

class KegiatanForm(forms.ModelForm):

	class Meta:
		model = Kegiatan
		fields = ['title']

class PesertaForm(forms.ModelForm):

	class Meta:
		model = Peserta
		fields = ['nama_peserta']

story6/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.views.generic import TemplateView
from .forms import KegiatanForm, PesertaForm
from .models import Kegiatan, Peserta


def kegiatan(request):
	events = Kegiatan.objects.all()
	pesertaForm = PesertaForm()
	return render(request, 'story6/listKegiatan.html', {'kegiatan' : events,'pesertaForm' : pesertaForm})

def tambahKegiatan(request) :
	if request.method == 'POST':
		form = KegiatanForm(request.POST)
		if form.is_valid():
			form.save()
			return redirect('story6:kegiatan')
	else:
		form = KegiatanForm()
	return render(request, 'story6/tambahKegiatan.html', {'form' : form})

def tambahPeserta(request,id) :
	if request.method == 'POST':
		form = PesertaForm(request.POST)
		if form.is_valid():
			kegiatan = get_object_or_404(Kegiatan, id=id)
			kegiatan.peserta_set.create(nama_peserta=form.cleaned_data.get('nama_peserta'))
			return redirect('story6:kegiatan')
	else:
		pesertaForm = PesertaForm()
	return render(request, 'story6/listKegiatan.html', {'pesertaForm' : pesertaForm})

def deleteKegiatan(request, id):
	kegiatan = get_object_or_404(Kegiatan, id=id)
	kegiatan.delete()
	return redirect('story6:kegiatan')

story6/templates/story6/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&family=Roboto&display=swap" rel="stylesheet">
    {% block style %}{% endblock style %}
	
	{% block title %}{% endblock title %}
</head>
<body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-container">
            <a class="navbar-brand" href="#"><img src="{% static 'story6/images/logo.png' %}"></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active mr-5">
                            <a class="nav-link" href="{% url 'story6:kegiatan' %}">Kegiatan<span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

	{% block content %}{% endblock content %}

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

	{% block script %}{% endblock script %}

	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>

    <meta name="description" content="Let's code!">
	<meta name="keywords" content="Universitas Indonesia, University of Indonesia, Computer Science">
	<meta name="author" content="Aynun Nissa">
</body>
</html>

story6/templates/story6/listKegiatan.html
{% extends "story6/base.html" %}
{% load static %}

{% block style %}<link rel="stylesheet" type="text/css" href="{% static 'story6/style.css' %}">{% endblock style %}

{% block title %}<title>List Kegiatan</title>{% endblock title %}

{% block content %}
	<div class="container">
		<a href="{% url 'story6:tambahKegiatan' %}"><button class="btn btn-danger tambahKegiatanButton">Tambah Kegiatan</button></a>
		<div class="row subjectCard activity">
			{% for kegiatan in kegiatan %}
			<div class="col col-10 col-md-2 card">
				<form action="{% url 'story6:deleteKegiatan' kegiatan.id %}" method="POST">
					{% csrf_token %}
					<button class="deleteKegiatan" type="submit">
						<div class="right"></div>
						<div class="left"></div>
					</button>
				</form>
				<button onclick="daftar('{{ kegiatan.id }}','{{ kegiatan.title }}')" class="kotak">Daftar</button>
					<img class="imageKegiatan" src="{% static 'story6/images/group.png' %}">
					<h1 class="subjectTitle">{{ kegiatan.title }}</h1>
					<h6>Peserta</h6>
					<ul>
						{% for peserta in kegiatan.peserta_set.all %}
							<li>{{ peserta.nama_peserta }}</li>
						{% endfor %}
					</ul>
			</div>
			{% endfor %}
		</div>
	</div>

	<div class="registerEvent">
		<button onclick="close()" class="deleteKegiatan" id="closeRegist" >
			<div class="right"></div>
			<div class="left"></div>
		</button>
		<div class="row">
			
			<div class="col col-12"><h3 class="titleEvent" style="text-align: center; padding: 10px"></h3></div>
			<div class="col col-10 offset-1">
				<form id="tambahPeserta" method="POST" action="">
					{% csrf_token %}
					<label for="id_nama_peserta">Nama :</label>
					{{ pesertaForm.nama_peserta }}
					<button style="margin: auto; margin-top: 20px; " class="btn btn-outline-danger" type="submit">Daftar Kegiatan</button>
				</form>
			</div>
		</div>
	</div>

{% endblock content %}

{% block script %}
	<script type="text/javascript">
		function daftar(e, title) {
			$(".registerEvent").css('display','block');
			$('#tambahPeserta').attr('action', "/tambahPeserta/" + e);
			document.getElementsByClassName('titleEvent')[0].innerText = title;
		}		
	</script>
	<script type="text/javascript">
		function close() {
			console.log("close");
			$(".registerEvent").css('display','none');
		}
	</script>
{% endblock script %}

story6/templates/story6/tambahKegiatan.html
{% extends "story6/base.html" %}
{% load static %}

{% block style %}<link rel="stylesheet" type="text/css" href="{% static 'story6/style.css' %}">{% endblock style %}

{% block title %}<title>Tambah Kegiatan</title>{% endblock title %}

{% block content %}
<div class="container tambahKegiatanPage">
	<div class="row">
		<div class="col col-10 col-md-6 offset-1 offset-md-3">
			<h1>Daftarkan Kegiatanmu!</h1>
			<form method="POST" action="{% url 'story6:tambahKegiatan' %}">
			{% csrf_token %}
			<p>{{ form.title }}</p>
			<button class="btn btn-outline-danger" type="submit">Tambah Kegiatan</button>
			</form>
		</div>
	</div>
</div>
{% endblock content %}